gcd:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/gcd gcd.hs
power:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/power power.hs
sandbox:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/sandbox sandbox.hs
.PHONY: gcd, power, sandbox