gcd:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/gcd gcd.hs
power:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/power power.hs
fib_matrix:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/fib_matrix fib_matrix.hs
perfect:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/perfect perfect.hs
collatz:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/collatz collatz.hs
delannoy:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/delannoy delannoy.hs
polinom:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/polinom polinom.hs
clone:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/clone clone.hs
zip:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/zip zip.hs
fib_list:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/fib_list fib_list.hs
sandbox:
	ghc -dynamic -no-keep-hi-files -no-keep-o-files -o ./bin/sandbox sandbox.hs
.PHONY: gcd, power, sandbox, fib_matrix, perfect, collatz, delannoy, polinom, clone, zip, fib_list